# Generated by Django 5.2.11 on 2026-02-18 13:30

from decimal import Decimal

from django.db import migrations

MONEY_PLACES = Decimal("0.01")


def _quantize(value: Decimal) -> Decimal:
    return value.quantize(MONEY_PLACES)


def backfill_vat_fields(apps, schema_editor):
    Cart = apps.get_model("productory_checkout", "Cart")
    Order = apps.get_model("productory_checkout", "Order")
    StoreConfig = apps.get_model("productory_core", "StoreConfig")

    config = (
        StoreConfig.objects.select_related("default_currency", "default_tax_rate")
        .order_by("id")
        .first()
    )

    if config and config.default_tax_rate_id and config.default_tax_rate.is_active:
        rate_percent = Decimal(config.default_tax_rate.rate_percent)
    else:
        rate_percent = Decimal("0.00")
    includes_vat = bool(config.price_includes_vat) if config else True
    currency_code = config.default_currency.code if config else "ZAR"
    multiplier = Decimal("1.00") + (rate_percent / Decimal("100.00"))

    for cart in Cart.objects.all().iterator():
        subtotal = Decimal(cart.subtotal_amount)
        total = Decimal(cart.total_amount)
        if rate_percent > Decimal("0.00") and includes_vat:
            subtotal_excl = _quantize(subtotal / multiplier)
            total_excl = _quantize(total / multiplier)
            subtotal_incl = subtotal
            total_incl = total
        elif rate_percent > Decimal("0.00"):
            subtotal_excl = subtotal
            total_excl = total
            subtotal_incl = _quantize(subtotal * multiplier)
            total_incl = _quantize(total * multiplier)
        else:
            subtotal_excl = subtotal
            total_excl = total
            subtotal_incl = subtotal
            total_incl = total

        cart.currency = currency_code
        cart.price_includes_vat = includes_vat
        cart.vat_rate_percent = _quantize(rate_percent)
        cart.subtotal_excl_vat_amount = subtotal_excl
        cart.subtotal_incl_vat_amount = subtotal_incl
        cart.total_excl_vat_amount = total_excl
        cart.total_incl_vat_amount = total_incl
        cart.tax_amount = _quantize(total_incl - total_excl)
        cart.subtotal_amount = subtotal_incl
        cart.total_amount = total_incl
        cart.discount_amount = _quantize(subtotal_incl - total_incl)
        cart.save(
            update_fields=[
                "currency",
                "price_includes_vat",
                "vat_rate_percent",
                "subtotal_excl_vat_amount",
                "subtotal_incl_vat_amount",
                "total_excl_vat_amount",
                "total_incl_vat_amount",
                "tax_amount",
                "subtotal_amount",
                "total_amount",
                "discount_amount",
                "updated_at",
            ]
        )

    for order in Order.objects.all().iterator():
        subtotal = Decimal(order.subtotal_amount)
        total = Decimal(order.total_amount)
        if rate_percent > Decimal("0.00") and includes_vat:
            subtotal_excl = _quantize(subtotal / multiplier)
            total_excl = _quantize(total / multiplier)
            subtotal_incl = subtotal
            total_incl = total
        elif rate_percent > Decimal("0.00"):
            subtotal_excl = subtotal
            total_excl = total
            subtotal_incl = _quantize(subtotal * multiplier)
            total_incl = _quantize(total * multiplier)
        else:
            subtotal_excl = subtotal
            total_excl = total
            subtotal_incl = subtotal
            total_incl = total

        order.currency = currency_code
        order.price_includes_vat = includes_vat
        order.vat_rate_percent = _quantize(rate_percent)
        order.subtotal_excl_vat_amount = subtotal_excl
        order.subtotal_incl_vat_amount = subtotal_incl
        order.total_excl_vat_amount = total_excl
        order.total_incl_vat_amount = total_incl
        order.tax_amount = _quantize(total_incl - total_excl)
        order.subtotal_amount = subtotal_incl
        order.total_amount = total_incl
        order.discount_amount = _quantize(subtotal_incl - total_incl)
        order.save(
            update_fields=[
                "currency",
                "price_includes_vat",
                "vat_rate_percent",
                "subtotal_excl_vat_amount",
                "subtotal_incl_vat_amount",
                "total_excl_vat_amount",
                "total_incl_vat_amount",
                "tax_amount",
                "subtotal_amount",
                "total_amount",
                "discount_amount",
                "updated_at",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("productory_core", "0002_seed_store_defaults"),
        ("productory_checkout", "0003_cart_price_includes_vat_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_vat_fields, migrations.RunPython.noop),
    ]
