# Generated by Django 5.2.11 on 2026-02-18 13:45

import productory_core.currency
import productory_core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productory_checkout', '0004_backfill_vat_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='currency',
            field=models.CharField(default=productory_core.currency.default_currency_code, max_length=3, validators=[productory_core.validators.validate_active_currency_code]),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default=productory_core.currency.default_currency_code, max_length=3, validators=[productory_core.validators.validate_active_currency_code]),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', '-updated_at'], name='prod_cart_status_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='prod_order_status_cre_idx'),
        ),
    ]
