# Generated by Django 5.2.11 on 2026-02-18 13:30

from decimal import Decimal

from django.db import migrations


def seed_store_defaults(apps, schema_editor):
    Currency = apps.get_model("productory_core", "Currency")
    TaxRate = apps.get_model("productory_core", "TaxRate")
    StoreConfig = apps.get_model("productory_core", "StoreConfig")

    currencies = [
        ("ZAR", "South African Rand", "R"),
        ("USD", "US Dollar", "$"),
        ("EUR", "Euro", "€"),
        ("GBP", "Pound Sterling", "£"),
    ]

    for code, name, symbol in currencies:
        Currency.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "symbol": symbol,
                "decimal_places": 2,
                "is_active": True,
                "is_default": code == "ZAR",
            },
        )

    vat_rate, _ = TaxRate.objects.update_or_create(
        code="ZA_VAT_STANDARD",
        defaults={
            "name": "South Africa VAT Standard",
            "country_code": "ZA",
            "rate_percent": Decimal("15.00"),
            "is_active": True,
            "is_default": True,
        },
    )

    default_currency = Currency.objects.get(code="ZAR")
    StoreConfig.objects.update_or_create(
        slug="default",
        defaults={
            "default_currency": default_currency,
            "default_timezone": "Africa/Johannesburg",
            "price_includes_vat": True,
            "default_tax_rate": vat_rate,
        },
    )


def reverse_store_defaults(apps, schema_editor):
    StoreConfig = apps.get_model("productory_core", "StoreConfig")
    TaxRate = apps.get_model("productory_core", "TaxRate")
    Currency = apps.get_model("productory_core", "Currency")

    StoreConfig.objects.filter(slug="default").delete()
    TaxRate.objects.filter(code="ZA_VAT_STANDARD").delete()
    Currency.objects.filter(code__in=["ZAR", "USD", "EUR", "GBP"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("productory_core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_store_defaults, reverse_store_defaults),
    ]
