# Generated by Django 5.2.11 on 2026-02-18 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productory_core', '0002_seed_store_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_label', models.CharField(max_length=120)),
                ('object_pk', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('relation_updated', 'Relation Updated')], max_length=20)),
                ('actor_display', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productory_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['model_label', 'object_pk', '-created_at'], name='prod_audit_lookup_idx')],
            },
        ),
    ]
