# Generated by Django 5.2.11 on 2026-02-18 13:30

import productory_core.currency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productory_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default=productory_core.currency.default_currency_code, max_length=3),
        ),
    ]
