# Generated by Django 5.2.11 on 2026-02-18 13:45

import productory_core.currency
import productory_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productory_catalog', '0002_alter_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default=productory_core.currency.default_currency_code, max_length=3, validators=[productory_core.validators.validate_active_currency_code]),
        ),
    ]
