name: Good first issue
description: Small scoped task suitable for new contributors
title: "good first issue: "
labels: ["good first issue"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task description
      description: Define expected outcome and acceptance criteria.
    validations:
      required: true
