# Generated by Django 5.2.11 on 2026-02-18 13:45

import productory_core.currency
import productory_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productory_catalog', '0003_alter_product_currency'),
        ('productory_promotions', '0002_alter_bundle_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='applies_to_all_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='currency',
            field=models.CharField(default=productory_core.currency.default_currency_code, max_length=3, validators=[productory_core.validators.validate_active_currency_code]),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'start_at', 'end_at'], name='productory_promo_window_idx'),
        ),
    ]
